### ISSUE TITLE
File

### ISSUE THREAD

**Issue by brhyanag** [khalsa/Movie-Recommender#1]
Hi

I'm testing your app but need  this file (movieFormatted.txt) to run, 

i need your help!

thanks

**Comment by khalsa** [comment]
You need to run below R script to generating that file.

https://github.com/khalsa/Movie-Recommender/blob/master/src/main/resources/RScript.txt


Similar genre movie will be clustered based on the K Means clustering algorithm.
And then Item-Item cosine similarity is applied on the filtered data based on the input movie cluster.

**Comment by brhyanag** [comment]
the file u.data, u.item are self-generated, because not find the path

String inputPath = "file:///C:/Saurabh/SparkTest/MovieUserInput/u.data";
String movieInput = "file:///C:/Saurabh/SparkTest/MovieUserInput/u.item";

ERROR´:Exception in thread "main" org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/C:/Saurabh/SparkTest/MovieUserInput/u.item

Thanks

**Comment by khalsa** [comment]
For SparkRecommendation.java data can be downloaded from below link :
http://grouplens.org/datasets/movielens/100k/

u.data has movie ratings
u.item has movie Id and Movie Name

For KMeansMovieSimilarity.java version use below link :-
http://grouplens.org/datasets/movielens/1m/

100k data was too sparse for K means.

**Comment by brhyanag** [comment]
thanks :)

**Comment by khalsa** [comment]
Resolved ;)
